name: Update Workflows JSON

on:
  push:
    branches: [main]

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: run script
        run: python update_menu.py

      - name: update and commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -n "$(git status --porcelain community_workflows.json)" ]; then
            git add .
            git commit -m "chore: update community_workflows.json"
            git push
          else
            echo "No changes in community_workflows.json."
          fi